service:
  name: ticketing.catalog
  version: 0.0.1
  address: ":50052"
  env: dev

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: your-password
  database: ticketing
  schema: identity
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 5m

redis:
  url: 'rediss://username:password@hostname:port'

log:
  level: debug
  format: console
