service:
  name: ticketing.notification
  version: 0.0.1
  address: ":50054"
  env: dev

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: your-password
  database: ticketing
  schema: notification
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 5m

redis:
  url: 'rediss://username:password@hostname:port'

etcd:
  endpoints:
    - "localhost:2379"
  username: "username"
  password: "password"

jwt:
  privateKey: ""
  publicKey: "your-public-key"
  accessTokenTtl: 15m
  refreshTokenTtl: 168h  # 7 days
  namespace: ticketing

log:
  level: debug
  format: console
