service:
  name: ticketing.identity
  version: 0.0.1
  address: ":50051"
  env: dev

database:
  host: 172.22.0.23
  port: 25432
  user: postgres
  password: root1234
  database: ticketing
  schema: identity
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 5m

redis:
  url: 'rediss://username:password@hostname:port'

etcd:
  endpoints:
    - "localhost:2379"
  username: "username"
  password: "password"

jwt:
  secret: your-super-secret-jwt-key-change-in-production
  access_token_ttl: 15m
  refresh_token_ttl: 168h  # 7 days
  issuer: ticketing

log:
  level: debug
  format: console
